import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link';
import './globals.css'
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] })

const links = [
  { href: '/', label: 'Home'},
  { href: '/newtodo', label: 'New'},
  { href: '/about', label: 'About'}
]

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}  bg-slate-300`} >
        <div>
          {children}
          <Toaster position="top-right" />
        </div>
      </body>
    </html>
  )
}
